scireum_volumes: &scireum_volumes
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
  - /root/.m2:/root/.m2
clone:
  git:
    image: plugins/git
    volumes: *scireum_volumes
pipeline:
  test:
    image: scireum/sirius-build
    commands:
      - mvn clean test
    volumes: *scireum_volumes
    when:
      event: pull_request
  compile:
    image: scireum/sirius-build
    commands:
      - mvn clean compile
    volumes: *scireum_volumes
    when:
      event: push
  package_tag:
    image: scireum/sirius-build
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean package -DskipTests
    volumes: *scireum_volumes
    when:
      event: tag
  package_master:
    image: scireum/sirius-build
    commands:
      - mvn clean package -DskipTests
    volumes: *scireum_volumes
    when:
      branch: master
      event: push
  publish_master:
    image: plugins/docker
    repo: scireum/woody
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    volumes: *scireum_volumes
    when:
      branch: master
      event: push
  publish_tag:
    image: plugins/docker
    repo: scireum/woody
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    volumes: *scireum_volumes
    when:
      event: tag
