version: "2"

services:
  mysql:
    image: mariadb:10.4
    ports:
      - "3306"
    volumes:
      - woody-dev-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    hostname: mysql
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123"
      - "9000"
    hostname: clickhouse
  redis:
    image: redis:3.2
    ports:
      - "6379"
    hostname: redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200"
    volumes:
      - woody-dev-es:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms128M -Xmx128M
    hostname: es
  s3:
    image: scireum/s3-ninja:5
    ports:
      - 80
    hostname: s3
volumes:
  woody-dev-mysql:
  woody-dev-es:
